// Placeholder Daprova mark (a short "pre" bar and a tall "post" bar) — the
// same geometry as public/daprova-mark.svg and the PNG embedded in reports,
// all generated by scripts/make-placeholder-logo.mjs. Swap all three when
// the real logo is ready.
export function DaprovaMark({ size = 20, className = '' }: { size?: number; className?: string }) {
  return (
    <svg width={size} height={size} viewBox="0 0 64 64" aria-hidden="true" className={className}>
      <rect width="64" height="64" rx="14" fill="#0e7c5a" />
      <rect x="15" y="30" width="13" height="20" rx="2.5" fill="#9fcfbf" />
      <rect x="36" y="14" width="13" height="36" rx="2.5" fill="#ffffff" />
    </svg>
  );
}
